
name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
      name: lint
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install miniconda
          uses: conda-incubator/setup-miniconda@v2
          with:
            miniconda-version: "latest"
            auto-update-conda: true
            python-version: "3.12"

        - name: Initialize conda environment
          run: make conda-create

        - name: Setup conda
          run: make conda-setup

        - name: Install conda dependencies
          run: make from-conda-lock

        - name: Poetry install
          run: make install

        - name: Style checks
          run: make check-codestyle
